name: emogotchi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  carousel_slider: ^5.0.0
  colorful_safe_area: ^1.0.0
  flutter:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  table_calendar: ^3.1.3
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  flutter_feather_icons: ^2.0.0
  path_provider: ^2.1.2
  provider:
  http:
  device_info_plus: ^11.2.0
  flutter_chat_bubble: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/background/
    - assets/dog/
    - assets/hamster/
    - assets/penguin/
    - assets/pig/
    - assets/penguin_egg/
    - assets/tiger/
    - assets/emoji/
    - assets/doctor.png
    - assets/homepage/
