name: emogotchi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  flutter_feather_icons: ^2.0.0
  path_provider: ^2.1.2
  provider:

flutter:
  uses-material-design: true
